version: "3"
services: 

    jupyter:
        image: jupyter/datascience-notebook:latest
        ports: 
            - 8888:8888
        volumes: 
            - .:/home/jovyan/work
        env_file: .env    
        working_dir: /home/jovyan/work
        command: jupyter lab --NotebookApp.token=''
